### ISSUE TITLE
How to use the landing layout?

### ISSUE THREAD

**Issue by MapuH** [kitian616/jekyll-TeXt-theme#106]
Thank you for the great theme. I'm trying to make use of the *landing* layout, but with no success. I can't understand what structure to follow under the **data** variable. Looking at *landing.html* I guess we should define different sections, but I can't figure it out:
```yaml
---
layout: landing
data:
    # ?????
---
```
