### ISSUE TITLE
能否添加正文grid支持

### ISSUE THREAD

**Issue by HenryQW** [kitian616/jekyll-TeXt-theme#13]
就像bootstrap grid一样，方便图片和文字并排

**Comment by kitian616** [comment]
你是指增加类似于 bootstrap grid 这样的 css class ，还是这像[这样](https://dribbble.com/shots/902148-Portfolio-Page-Alternative-Skin)的 layout ？

**Comment by WangQiru** [comment]
@kitian616 和bootstrap一样的responsive CSS class即可, 如 .col-md-6

**Comment by kitian616** [comment]
I'm planning to add a `portfolio` layout, this could add together.

**Comment by HenryQW** [comment]
基主说好的grid呢！我自己魔改的
<img width="813" alt="screen shot 2018-04-20 at 11 44 20" src="https://user-images.githubusercontent.com/5896343/39047210-f6053808-4490-11e8-8d37-8b55faa605ab.png">
<img width="813" alt="screen shot 2018-04-20 at 11 51 25" src="https://user-images.githubusercontent.com/5896343/39047269-346720fc-4491-11e8-8191-c3066c085c27.png">

```css
.evenly-distributed-children-2 figure, .evenly-distributed-children-3 figure{
      display: inline-block;
      vertical-align: top;
      overflow-x: auto;
      width:100%;
}

@media screen and (min-width: 830px) {
  .evenly-distributed-children-3 figure {
      width: 32%;
  }
}

@media screen and (min-width: 600px) and (max-width: 830px) {
  .evenly-distributed-children-3 figure {
      width: 45%;
  }
}

@media screen and (min-width: 600px) {
  .evenly-distributed-children-2 figure {
      width: 48%;
  }

.evenly-distributed-children-2 figure:last-child{
      margin-left: 10px;
  }
}
```
修改 https://github.com/kitian616/jekyll-TeXt-theme/blob/55003d265269ac2a555153a6f07414ddb8a50c35/_includes/scripts/page-post-common.js#L16 
```js
$articleContent.find('.highlight').each(function() {
```
