### ISSUE TITLE
Feature request: A sample index.html

### ISSUE THREAD

**Issue by adibrastegarnia** [kitian616/jekyll-TeXt-theme#147]
## Description
Hello, 
Would you please post a sample of index.html layout that you used for the theme website? Defining a layout like you used for the website is not straightforward. 
In addition, how can I change the menu on top of the first page to add new pages?

**Comment by kitian616** [comment]
- you mean landing layout? It's on the way.
- I don't quite understand your second question, what do you mean by "the menu on top of the first page"?

**Comment by janash** [comment]
@adibrastegarnia 

I think I understand the question you are asking - you would like a layout similar to the example site. Below is the solution I found for making my site fit this layout.

1. See Issue #106 for a sample landing layout. Add this to your repository in the top level, and this will replace the `index.html` file so that this is the first page people will see when they go to your website. If you would like your menu to show up on the landing page, go to `_layouts/landing.html`, and change `header: false` to `header: true` on line 3.

2. To add new pages to the menu, edit `data/navigation.yml` as explained on the documentation website. 
https://tianqi.name/jekyll-TeXt-theme/docs/en/navigation

3. If you would like the "home" button to still show a blog instead of the landing page, you will need to move some files and change some things in the `_data/navigation.yml` file and the `_config.yml` file.

- create a directory called `blog` (ie `mkdir blog`)
- copy your `index.html` file into `blog` (ie, `cp index.html blog/`)
- To have this show up on the menu, `_data/navigation.yml` add
```
  - title:      Home
    url:        /blog/
```
- In the `index.html` file, set the 'home' path to `/blog` (line 66)

```
paths:
  root    : # title link url, "/" (default)
  home    : /blog/ # home layout url, "/" (default)
```
- Change the path under paginate to point to these posts (changed value shown below)

```
## => Paginate
##############################
paginate: 8
paginate_path: /blog/page:num # don't change this unless for special need
```

- Change your `defaults` section to point to this directory

```
defaults:
  ## home
  - scope:
      path: "blog"
    values:
      articles:
        excerpt_type: html
  ## posts
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
```

Making these changes, your site will automatically direct to a landing page. The text on the left menu ("Your site title" will go to your landing page, while on the right, the "Home" menu item will go to what was originally the default index (blog posts).) Hope this helps
