### ISSUE TITLE
Feature request: centering mermaid graphs

### ISSUE THREAD

**Issue by ziofil** [kitian616/jekyll-TeXt-theme#156]
## Description

At the moment the mermaid graphs and charts are aligned all the way to the left margin (see screenshot). How to center them on the page?

<img width="1139" alt="capture d ecran 2019-02-19 a 16 23 54" src="https://user-images.githubusercontent.com/8944955/53026261-d8306380-3462-11e9-9530-33a7e739217a.png">

**Comment by HenryQW** [comment]
Customise CSS before the author adds the centering option:

```css
code.language-chart[data-processed] {
    display: grid;
    justify-content: center;
}
```
