### ISSUE TITLE
功能请教：首页图片和文字用grid 卡片式展示的设置

### ISSUE THREAD

**Issue by 0lidaxiang** [kitian616/jekyll-TeXt-theme#159]
如题，首页图片和文字用grid 卡片式展示 如何使用？貌似我改动了layout里面的home.html 改成

```
---
layout: articles
title: Articles - Item (Cover)
articles:
  data_source: site.sample_page
---
```
没有这个效果，反而文章列表不见了。

**Comment by HenryQW** [comment]
试试看把
`data_source: site.sample_page` 
改为:
`data_source: site.posts`

**Comment by 0lidaxiang** [comment]
@HenryQW 改成posts以后可以看到文章列表，但是没有grid 卡片的效果了。

**Comment by kitian616** [comment]
@0lidaxiang 卡片效果是 `type` 指定的，`data_source` 是数据源。

```yml
layout: articles
title: Articles - Grid
articles:
  data_source: site.sample_page
  type: grid
```
https://tianqi.name/jekyll-TeXt-theme/articles/grid.html
