### ISSUE TITLE
Bug:默认设置下，Page - Single并不是居中

### ISSUE THREAD

**Issue by ehds** [kitian616/jekyll-TeXt-theme#163]
**Description**

默认设置下，Page - Single并不是居中

配置文件：
```
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: false
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
```

**Expected behavior**
如何能达到您演示页这种效果呢？

**Screenshots (If Necessary)**

[默认配置下我的article页面.]
![image](https://user-images.githubusercontent.com/17853449/54141029-d6edc780-445f-11e9-9657-fd0c5c0a0208.png)
页面并不居中，而且右边还会存在一个sidebar的控件，虽然没有显示。

[您演示页下single-article页面.]
![image](https://user-images.githubusercontent.com/17853449/54141066-eec54b80-445f-11e9-888b-2ad2f83d40c5.png)
是居中的。
**Environment (If Necessary)**

OS: Windows10
Ruby: ruby 2.5.1p57
jekyll 3.8.5
Broser: Firefox
