### ISSUE TITLE
Listing Articles

### ISSUE THREAD

**Issue by bitVivAZ** [kitian616/jekyll-TeXt-theme#178]
Good day, 
I just want to know if someone could help regards to showing the articles created.
At the moment on my home page you are able to see the article headers but no images. 
I'm trying to replicate the gird view so my front matter is:

```
layout: home

title: Welcome
article_header:
  type: overlay
  theme: dark
  background_image:
    src: /assets/home/header.jpg

articles:
  type: grid
  show_excerpt: true
  show_readmore: true
  show_info: true

````

on my blog page i want to replicate the "Articles - Item (Cover + Excerpt + Read More)" sample and my front matter is 

```
layout: articles
title: Articles - Item (Cover + Excerpt + Read More + Info)
articles:
  data_source: site.sample_page
  show_excerpt: true
  show_readmore: true
  show_info: true
```

 
However here nothing is showing..

my repo can be found at https://github.com/bitVivAZ/blog
or you can live version at https://bitvivaz.com/blog 

Thanks!
