### ISSUE TITLE
Feature request: Urls inside header localization

### ISSUE THREAD

**Issue by avently** [kitian616/jekyll-TeXt-theme#187]
Now I can easily make header titles in different languages. But how to localize urls for pages inside the header?

This is what I can do now:
```
header:
  - titles:
      en: &EN       Docs
      ru: &RU       Мануал
    key: docs
    url: /en/docs
```
Static link to engilsh version but title can be on russian. How to make a link to russian version too?

Something like that would be good:
```
header:
  - titles:
      en: &EN       Docs
      ru: &RU       Мануал
    key: docs
    urls:
      en: &EN       /en/docs
      ru: &RU       /ru/docs
```
