### ISSUE TITLE
当我添加一个主题没有的author link的时候，无法生效

### ISSUE THREAD

**Issue by qbycs** [kitian616/jekyll-TeXt-theme#225]
主题开发者，你好。

当我想添加一个该主题没有的作者社交链接（Researchgate平台，一个科研工作者的平台）时，发现难以生效。

我先在_includes\author_link.html中添加了以下代码（完全仿照例如weibo的链接语法，因为我是个纯小白）：

```html
   {%- if _author.researchgate -%}
      <li title="{{ _locale_string_follow | replace: '[NAME]', 'Researchgate' }}">
        <a class="button button--circle researchgate-button" itemprop="sameAs" href="https://researchgate.com/{{ _author.researchgate }}" target="_blank">
          <div class="icon">{%- include svg/icon/social/researchgate.svg -%}</div>
​        </a>
​      </li>
​    {%- endif -%}

```

同时在_config.yml中也添加了  *researchgate :  user name* ，以及在includes\svg\icon\social中也添加了researchgate.svg图标元素，然后网站中的确出现了researchgate的连接，可以点击，功能一切正常，除了缺少圆形背景。

然后，研究后发现还需要在_site\assets\css\mian.css中编辑，然后我又添加了一下代码，位置位于weibo站点圆形背景指定语法之后（同样模仿了weibo的语法，自己仅指定了背景色）：

```css
.author-links > ul > li > .researchgate-button {
    -webkit-transition: all 0.2s ease-in-out;
    transition: all 0.2s ease-in-out; }
    .author-links > ul > li > .researchgate-button svg path {
      -webkit-transition: all 0.2s ease-in-out;
      transition: all 0.2s ease-in-out; }
    .author-links > ul > li > .researchgate-button, .author-links > ul > li > .researchgate-button:link, .author-links > ul > li > .researchgate-button:visited {
      color: #fff;
      background-color: #dd977d; }
      .author-links > ul > li > .researchgate-button svg path, .author-links > ul > li > .researchgate-button:link svg path, .author-links > ul > li > .researchgate-button:visited svg path {
        fill: #fff; }
    .root[data-is-touch="false"] .author-links > ul > li > .researchgate-button:hover {
      color: #fff;
      background-color: #a6715e; }
      .root[data-is-touch="false"] .author-links > ul > li > .researchgate-button:hover svg path {
        fill: #fff; }
    .root[data-is-touch] .author-links > ul > li > .researchgate-button.active, .root[data-is-touch] .author-links > ul > li > .researchgate-button:active {
      color: #fff;
      background-color: #6f4C3f; }
      .root[data-is-touch] .author-links > ul > li > .researchgate-button.active svg path, .root[data-is-touch] .author-links > ul > li > .researchgate-button:active svg path {
        fill: #fff; }
    .root[data-is-touch] .author-links > ul > li > .researchgate-button.focus {
      color: default;
      background-color: #a6715e;
      box-shadow: 0 0 0 2px rgba(166, 113, 94, 0.4); }
      .root[data-is-touch] .author-links > ul > li > .researchgate-button.focus svg path {
        fill: default; }
    .author-links > ul > li > .researchgate-button.disabled, .author-links > ul > li > .researchgate-button:disabled {
      color: rgba(255, 255, 255, 0.2) !important;
      background-color: #dd977d !important; }
      .author-links > ul > li > .researchgate-button.disabled svg path, .author-links > ul > li > .researchgate-button:disabled svg path {
        fill: rgba(255, 255, 255, 0.2) !important; }
```

之后，在本地jekyll编译中，researchgate图标终于有圆形背景了，但是发现了上传到github上之后博客网页仍然没有圆形背景，请问作者我那里做的不对？或者是还需要做些什么？

[Description of the feature]
