### ISSUE TITLE
如何添加 除了 Home All About RSS 的新标签？

### ISSUE THREAD

**Issue by YinlinHu** [kitian616/jekyll-TeXt-theme#25]
Kitian 你好，你的主题非常不错，因为我非前端人士，所以问的问题比较初级。多谢了。

**Comment by kitian616** [comment]
通过 nav_lists 来配置的。[示例](https://github.com/kitian616/jekyll-TeXt-theme/blob/master/_config.yml#L21)，类似这样的：
```
nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html
  - title: New
     url: /new.html
```
