### ISSUE TITLE
Bug: invalid byte sequence in UTF-8 in /_layouts/page.html

### ISSUE THREAD

**Issue by HujinoKun** [kitian616/jekyll-TeXt-theme#268]
Hello,

after modifying the files that can be modified by following your tutorial. I encounter the following problem when launching my docker-compose.

```
jekyll-test |   Liquid Exception: invalid byte sequence in UTF-8 in /_layouts/page.html
jekyll-test |                     ------------------------------------------------
jekyll-test |       Jekyll 4.0.0   Please append `--trace` to the `serve` command 
jekyll-test |                      for any additional information or backtrace. 
jekyll-test |                     ------------------------------------------------`
```
my docker-compose.yml :

```
version: '3.5'
services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-test
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: jekyll build --watch --force_polling --verbose
```

- OS: Fedora 31
- Ruby: 2.7
- Jekyll: 4.0.0
- Browser: Firefox
