### ISSUE TITLE
RSS error

### ISSUE THREAD

**Issue by bateria2x100** [kitian616/jekyll-TeXt-theme#29]
The RSS section is not build ok... just 9 records... please any ideas ?

**Comment by WangQiru** [comment]
1. Owner's production RSS is [down](https://tianqi.name/feed.xml). 
2. Per [jekyll-feed specs](https://github.com/jekyll/jekyll-feed/blob/master/lib/jekyll-feed/feed.xml#L42), relative path in image src is surprisingly not supported by many RSS readers (Reeder and Selfoss).

But I guess RSS is dying...

**Comment by bateria2x100** [comment]
But i need an rss to generate my feed of a podcast... any alternatives to do that ?

**Comment by kitian616** [comment]
@bateria2x100 maybe you can try [this](https://github.com/snaptortoise/jekyll-rss-feeds)

**Comment by bateria2x100** [comment]
Thannks a lot !! Worked !!!!!

Great work, love your theme !!!!

(One question…where to setup the navigation bar ? I want to add a search page and change some names in spanish… ) I did it a few days but can t find where the hell is.,. !!

THANK YOU !

------------------------------------------------------------
Bateria2x100@gmail.com
@bateria2x100
https://www.bateria2x100.com

**Comment by WangQiru** [comment]
It’s in _config.yml

```
nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html
  - titles:
      en: Hello
      zh: 你好
      es: Holá
    url: /hola.html
```

**Comment by bateria2x100** [comment]
Um…rare… not working on my page..
I just want to add one more page called “Buscar” (search), it is on /search/index.html…

_config.yml
nav_lists:
  - titles:
      en: Buscar
       url: /search/index.html
  - titles:
      en: About
      url: /about.html


What am i doing wrong ?

I ve seen this file also :

_data/locale.yml  -> What is this file to ?

Thanks again and sorry…i m not an expert...

------------------------------------------------------------
Bateria2x100@gmail.com
@bateria2x100
https://www.bateria2x100.com

**Comment by kitian616** [comment]
```
nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html
  - title: Buscar
    url: /search/index.html
```
watch out the indentation.

if you don't wan't multi language, just use `title`.  

no need to feel sorry about having a problem, just ask.
