### ISSUE TITLE
Question: nav_list fixed number?

### ISSUE THREAD

**Issue by maddovr** [kitian616/jekyll-TeXt-theme#59]
So I made a page where I want to list my projects and I wanted to show it on the novelist in the top-right corner, however it doesn't seem to work unless I replace the about link. Am I doing something wrong(quite possible, since I've a high fever)? How can I go about it the right way?

**Comment by kitian616** [comment]
maybe you should set the nav configs in `_config.yml` like this:

```yaml
nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html
  - title: Projects
    url: /projects.html
```
This add a "Projects" link on the navigator, and url is "/projects.html"
