### ISSUE TITLE
Can't show disqus

### ISSUE THREAD

**Issue by turing4ever** [kitian616/jekyll-TeXt-theme#79]
Hi, 

I tried to enable comments on my site, followed the instructions and updated my `_config.yml`:   
```YAML
provider: disqus
disqus:
  shortname: my_disqus_site_name
```
However, comment area still won't show up on my site. Is there anything else I need to change?
